<a href="https://colab.research.google.com/github/AJuliPS/AI2023-2_JulianaPonce/blob/main/Numpy-OperaciosAritmeticas06112023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**OPERACIONES ARITMÉTICAS**

In [ ]:
import numpy as np

In [ ]:
#CREATE AN ARRAY WITH RANDOM INTEGER VALUES BETWEEN 1 AND 10
a=np.random.randint(1, 11, size=(3, 4))
b=np.random.randint(1, 11, size=(3, 4))

print('-------------------------------------------')
print(a)

print('-------------------------------------------')
print(b)

print('-------------------------------------------')
print(a.shape)
print(b.shape)

print('-------------------------------------------')
print('Sumar números')
print(a+b)

print('-------------------------------------------')
print('Substracción de números')
print(a-b)

print('-------------------------------------------')
print('Sumar números')
print(np.add(a,b))

print('-------------------------------------------')
print('Multiplicación de números')
print(np.multiply(a,b))

print('-------------------------------------------')
print('División de números')
print(np.divide(a,b))



-------------------------------------------
[[10 10  9  8]
 [ 2  7 10  3]
 [ 8  1  8  2]]
-------------------------------------------
[[ 5  6  8  6]
 [ 6  6  2  9]
 [ 5  3 10  9]]
-------------------------------------------
(3, 4)
(3, 4)
-------------------------------------------
Sumar números
[[15 16 17 14]
 [ 8 13 12 12]
 [13  4 18 11]]
-------------------------------------------
Substracción de números
[[ 5  4  1  2]
 [-4  1  8 -6]
 [ 3 -2 -2 -7]]
-------------------------------------------
Sumar números
[[15 16 17 14]
 [ 8 13 12 12]
 [13  4 18 11]]
-------------------------------------------
Multiplicación de números
[[50 60 72 48]
 [12 42 20 27]
 [40  3 80 18]]
-------------------------------------------
División de números
[[2.         1.66666667 1.125      1.33333333]
 [0.33333333 1.16666667 5.         0.33333333]
 [1.6        0.33333333 0.8        0.22222222]]


In [ ]:
a=np.random.randint(1, 11, size=(2, 3))
b=np.random.randint(1, 11, size=(3, 4))
print(a.shape)
print(b.shape)
print('-------------------------------------------')
print(np.dot(a,b))
print('-------------------------------------------')
print(a.dot(b))
print('-------------------------------------------')


(2, 3)
(3, 4)
-------------------------------------------
[[ 75  68 107 122]
 [ 29  24  50  39]]
-------------------------------------------
[[ 75  68 107 122]
 [ 29  24  50  39]]
-------------------------------------------


In [ ]:
#MATRIZ DE 2X2 TRANSPUESTA
a=np.random.randint(1, 11, size=(2, 2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[ 4  5]
 [10  8]]
[[ 4 10]
 [ 5  8]]


In [ ]:
#MATRIZ X 4 FILAS 3 COLUMNAS
a=np.random.randint(1, 11, size=(4, 3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('-------------------------------------------')
print(c)




(4, 3)
(3,)
[[ 3 10  8]
 [ 7  8  6]
 [ 9  1  6]
 [ 9  1  5]]
[1 0 2]
(4, 3)
[[ 4 10 10]
 [ 8  8  8]
 [10  1  8]
 [10  1  7]]
-------------------------------------------
[[ 3  7 10]
 [ 8  6  7]
 [ 3  6  8]
 [ 8  1  7]]


In [ ]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)
print('-------------------------------------------')
c=a+b
print(c)

[[ 3 10  8]
 [ 7  8  6]
 [ 9  1  6]
 [ 9  1  5]]
[1 0 2]
[[ 4 10 10]
 [ 8  8  8]
 [10  1  8]
 [10  1  7]]
-------------------------------------------
[[ 4 10 10]
 [ 8  8  8]
 [10  1  8]
 [10  1  7]]


In [ ]:
#crear matriz de 6x3 que tengan los mismos valores 1,2,3

a = np.full((6, 3), [1, 2, 3])
print(a)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


***Función tile***

In [ ]:
a=np.array([1,2,3])
#print(a)

tmp=np.tile(a, (6,1)) #TILE se utiliza para repetir una matriz o vector un número determinado de veces
print(tmp)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#matriz de 6x6 que los numeros sean enteros
a=np.random.randint(0, 10, size=(6,6))
print(a)

print('-------------------------------------------')

#PROMEDIO
aux=np.mean(a)
print(aux)
print('-------------------------------------------')

#COMO OBTENER EL PROMEDIO POR FILA
print(a.mean(axis=1))

print('-------------------------------------------')
#COMO OBTENER EL PROMEDIO POR COLUMNA
print(a.mean(axis=0))



[[4 6 1 4 4 9]
 [2 6 2 5 9 6]
 [6 8 1 5 9 2]
 [9 6 2 2 6 8]
 [9 2 7 7 1 1]
 [7 3 9 5 6 6]]
-------------------------------------------
5.138888888888889
-------------------------------------------
[4.66666667 5.         5.16666667 5.5        4.5        6.        ]
-------------------------------------------
[6.16666667 5.16666667 3.66666667 4.66666667 5.83333333 5.33333333]
