<a href="https://colab.research.google.com/github/AJuliPS/AI2023-2_JulianaPonce/blob/main/NumPyExercisesforDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [6]:
# 1. Import numpy as np and see the version
import numpy as np

!python --version

Python 3.10.12


In [ ]:
# 2. Create a 1D array of numbers from 0 to 9
lista1D = list(range(10))
print(lista1D)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# 3. Create random vector of size 10 and replace the maximum value by 0
import random

# Crear un vector aleatorio de tamaño 10
random_vector = [random.randint(1, 100) for _ in range(10)]

# Encontrar el valor máximo y su índice
max_value = max(random_vector)
max_index = random_vector.index(max_value)

# Reemplazar el valor máximo por 0
random_vector[max_index] = 0

print("Vector aleatorio con el valor máximo reemplazado por 0:")
print(random_vector)



Vector aleatorio con el valor máximo reemplazado por 0:
[3, 47, 7, 42, 10, 72, 84, 73, 85, 0]


In [ ]:
# 4. Print the number 8 from the array below: arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Acceder al elemento en la fila 1 (segunda fila) y columna 2 (tercera columna)
elemento = arr[1, 2]
print("Número 8 en la matriz arr:", elemento)



Número 8 en la matriz arr: 8


In [ ]:
# 5. Print the numbers [3, 4, 5] from the array below: arr = np.array([1,2,3,4,5,6,7])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

subset = arr[2:5] # Utiliza el corte para obtener los números deseados

print("Números [3, 4, 5] de la matriz arr:", subset)


Números [3, 4, 5] de la matriz arr: [3 4 5]


In [ ]:
# 6. Print the last 4 numbers from the array below: arr = np.array([1,2,3,4,5,6,7])
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Se usa el menos para obtener los 4 últimos números
ult4num = arr[-4:]

print("Los 4 últimos números del array arr:", ult4num)


Los 4 últimos números del array arr: [4 5 6 7]


In [ ]:
# 7. Create a 3×3 numpy array of all True’s
tmp= np.ones((3, 3), dtype=bool)
print(tmp)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# 8. Extract all odd numbers from array

array1D = np.array([i for i in range(10)])

numImpares = array1D[array1D % 2 != 0]

print("Matriz original:", array1D)
print("Números Impares:", numImpares)

Matriz original: [0 1 2 3 4 5 6 7 8 9]
Números Impares: [1 3 5 7 9]


In [ ]:
# 9. Crea un vector con valores comprendidos entre 10 y 49 (★☆☆).
vector = np.arange(10, 50) #ARANGE: crear secuencias de números dentro de un rango específico

print("Vector con valores entre 10 y 49:")
print(vector)



Vector con valores entre 10 y 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 10. Reverse a vector (first element becomes last)
original_vector = [1, 2, 3, 4, 5]

vectorInvertido = original_vector[::-1]

print("Vector Original:", original_vector)
print("vector Invertido:", vectorInvertido)


Vector Original: [1, 2, 3, 4, 5]
vector Invertido: [5, 4, 3, 2, 1]


In [ ]:
#  11. Create a 10x10 array with random integer values and find the minimum and maximum values
array = np.random.randint(0, 101, size=(10, 10))

# Find the minimum and maximum values
minV = np.min(array)
maxV= np.max(array)

print("Random 10x10 array:")
print(array)
print("Minimum value:", minV)
print("Maximum value:", maxV)


Random 10x10 array:
[[ 33  30  16  18  21   5  18  45   6  10]
 [ 43  39  55  50  70  53  27  34  48  35]
 [ 14  76  79  65  97  26  23  29  74   6]
 [ 21  89  64   7  33  99  95  23  88  91]
 [ 59  93  21  96   4  17   3   8   6  88]
 [ 70  34  24  62 100  96  97  63  63   1]
 [ 20  49  86   5  90  79  95  94  73  81]
 [ 94  60  67  93  37  22  32  76  14  35]
 [ 91  83  66  80  71  81   7  33  83  40]
 [ 69  96  55  26  68  82  23  14  94  65]]
Minimum value: 1
Maximum value: 100


In [ ]:
# 12. Create a 3x3x3 array with random values
array = np.random.rand(3, 3, 3)
print(array)


[[[0.31813911 0.2146331  0.84303186]
  [0.74562172 0.01298266 0.90930126]
  [0.91241528 0.56780662 0.60820178]]

 [[0.69024939 0.28479859 0.36625704]
  [0.42389467 0.40697329 0.19640948]
  [0.56195567 0.64447057 0.74239324]]

 [[0.13588317 0.50877075 0.1029754 ]
  [0.91499314 0.65670719 0.70574774]
  [0.20373873 0.7964503  0.76281995]]]


In [ ]:
# 13. Replace all odd numbers in arr with -1
array1D[array1D % 2 != 0] = -1
print("Matriz modificada:", array1D)

Matriz modificada: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# 14. Create an array of type float
float_array = np.array([1.0, 2.5, 3.7, 4.2, 5.9], dtype=float)
print(float_array)


[1.  2.5 3.7 4.2 5.9]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
array2D = array1D.reshape(2, -1)  # El '-1' de reshape infiere automáticamente el número de columnas

print("Matriz 2D remodelada con 2 filas:")
print(array2D)

Matriz 2D remodelada con 2 filas:
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


In [ ]:
# ¿Cómo encontrar valores comunes entre dos matrices?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common_values = np.intersect1d(Z1, Z2)

print("Array Z1:", Z1)
print("Array Z2:", Z2)
print("Common values:", common_values)

Array Z1: [7 3 4 2 7 2 9 5 9 9]
Array Z2: [2 7 5 5 9 3 1 4 2 6]
Common values: [2 3 4 5 7 9]


In [ ]:
#  Consider two random array A and B, check if they are equal


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Check if A and B are equal element-wise
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)

if are_equal:
    print("Las matrices A y B son iguales.")
else:
    print("Las matrices A y B no son iguales.")

Array A: [0 1 1 0 0]
Array B: [0 1 0 0 1]
Las matrices A y B no son iguales.


In [ ]:
# Stack arrays a and b vertically

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apila las matrices verticalmente
result = np.vstack((a, b))

print("Resultado de apilar a y b verticalmente:")
print(result)


Resultado de apilar a y b verticalmente:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Stack the arrays a and b horizontally.

# Supongamos que tenemos dos matrices a y b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apila las matrices horizontalmente
resultado = np.hstack((a, b))

print("Resultado de apilar a y b horizontalmente:")
print(resultado)


Resultado de apilar a y b horizontalmente:
[1 2 3 4 5 6]


In [ ]:
# Get all items between 5 and 10 from array tmp.
tmp = np.arange(15)
# Use boolean indexing to get items between 5 and 10
result = tmp[(tmp >= 5) & (tmp <= 10)]
print(result)


[ 5  6  7  8  9 10]


In [17]:
# How to make a python function that handles scalars to work on numpy arrays?
# ¿Cómo hacer que una función python que maneja escalares funcione con matrices numpy?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

#def maxx(x, y):
#    """Consigue el máximo de dos items"""
#    if x >= y:
#        return x
#    else:
#        return y

#maxx(1, 5)


def pair_max(a, b):
    # Utiliza la función numpy.maximum para obtener el máximo elemento a elemento
    result = np.maximum(a, b)
    return result

# Ejemplo de uso
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

output = pair_max(a, b)
print(output)

def maxx(x, y):
    """Consigue el máximo de dos items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

[6 7 9 8 9 7 5]


5

In [7]:
# Swap columns 1 and 2 in the array arr.
#Intercambia las columnas 1 y 2 del array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.array([[0, 2, 1], [3, 5, 4],[6, 8, 7]])

# Intercambiar las columnas 1 y 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print(arr)


[[2 0 1]
 [5 3 4]
 [8 6 7]]


In [8]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Crea un array 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]


array_aleatorio = np.random.uniform(5, 10, size=(5, 3))

print(array_aleatorio)


[[7.62292643 5.02748551 7.2822462 ]
 [9.2219902  6.35752053 6.75425615]
 [5.37441254 7.75996825 5.02302595]
 [9.2260829  7.68076557 5.58266866]
 [8.01129347 5.97623315 7.78665529]]
