<a href="https://colab.research.google.com/github/AJuliPS/AI2023-2_JulianaPonce/blob/main/NumpyActivity1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as juliana

aux=juliana.array([1,2,4,5])
print(aux)
print(aux.shape) #SHAPE: Devuelve una lista finita de elementos.

print('-------------------------')

aux=juliana.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))

print('-------------------------')

tmp=juliana.zeros((4,4))
print(tmp)

print('-------------------------')

tmp=juliana.full((4,4),5)
print(tmp)

print('-------------------------')

tmp=juliana.eye(4,4)
print(tmp)

print('-------------------------')

tmp=juliana.ones((4,4))
print(tmp)



[1 2 4 5]
(4,)
-------------------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
-------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#matriz de 3x3 de números aleatorios

tmp=10*juliana.random.random((3,3))
print(tmp)


[[4.47763508 9.21443388 6.09512002]
 [7.14786579 3.69304509 0.99403671]
 [0.20062445 7.34340752 7.70245712]]


In [ ]:
#extraer matriz de los números aleatorios

print(tmp[:2,:2])

[[4.47763508 9.21443388]
 [7.14786579 3.69304509]]


In [ ]:
#extraer matriz de los números aleatorios

print(tmp[:2,1:3])

[[9.21443388 6.09512002]
 [3.69304509 0.99403671]]


In [ ]:
#extraer de la matriz un número aleatorio

print(tmp[1,1])

3.6930450928532874


In [ ]:
#extraer de la matriz un número aleatorio

print(tmp[2,2])

7.702457116801891


In [ ]:
#matriz de 3x3 de números aleatorios

tmp=10*juliana.random.random((3,3))
print(tmp)

[[5.17644353 5.56327989 1.83232917]
 [3.74344802 6.79665717 3.33690742]
 [7.6098286  0.67064197 5.08733994]]


In [ ]:
filter=tmp>5
print(tmp[filter])

[5.17644353 5.56327989 6.79665717 7.6098286  5.08733994]


In [ ]:
#como filtrar Valores de 2 a 4
filter=(tmp>=2)&(tmp<=4)
print(tmp[filter])

[3.74344802 3.33690742]


In [ ]:
#matriz de 4x4 de números enteros

tmp=juliana.random.randint(0, 50, (4,4))
print(tmp)

print('-------------------------')

filter=juliana.mod(tmp, 2)==0
print(tmp[filter])

[[30  5 47 35]
 [41  5 40 44]
 [ 7 38  4 37]
 [ 0 28  7  6]]
-------------------------
[30 40 44 38  4  0 28  6]
